### ISSUE TITLE
Does this work in non-React setups?

### ISSUE THREAD

**Issue by tflx** [maraisr/storybook-addon-grid#14]
### Describe the bug

I tried to inlcude this in a web-components setup. Had to fiddle with your package.json in node_modules because of some nodejs/export error (don't know what that's about yet).

But once I had Storybook running the console gave me: "Can't perform a React state update on an unmounted component. …"
It's a new and very basic project (only one component)

Have you or anyone tested it with Web components or other frameworks.

*edit
The nodejs error is probably because I use Vite as Storybook builder. Apparently the exports in package.json is missing "." export. Deleting the whole "exports" part from package.json resolves it.
I don't know if this has anything to do with the error i mentioned onced it is up and running.

### To reproduce

Set up a new Web components project with Storybook and include the add-on.

### Expected behavior

A working add-on :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/maraisr/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/maraisr/.github/blob/main/CONTRIBUTING.md).
- [X] Is there already an issue for this?

**Comment by maraisr** [comment]
I highly suspect this is a vite bug and not a react related thing.

I'll for sure check it out, thanks for flagging! 💕

**Comment by mantismamita** [comment]
I have a similar problem using it with svelte and vite as a builder. The error is 
```
[vite] Internal server error: Missing "./dist/config/index.js" export in "storybook-addon-grid" package
```

**Comment by maraisr** [comment]
@mantismamita I have shipped a version 0.3.1 that should fix that issue.

@lukemcd-hero to your problem, this package [doesn't depend directly on react](https://github.com/maraisr/storybook-addon-grid/blob/3b9fda6b99d038a8becf92322864f01db2a5e37d/package.json#L91-L92). It's a peer dev and support 17 and above. That being said, I have just pushed a version to address the `useEffect` render bug, lame StrictMode double render shenanigans. Also so please look out for v0.3.1 🚀

**Comment by mantismamita** [comment]
I installed the new version but am still getting the exact same error which is odd since `./dist/config/index.js`is clearly present.

**Comment by lukemcd-hero** [comment]
@maraisr the 3.1 update resolves the console log error I had been seeing. Thanks!

**Comment by mantismamita** [comment]
@tflx yes, eventually there may be more people using vite and non-React setups but for now we're in the minority.

**Comment by maraisr** [comment]
I'm opening this issue again, noticed it wasn't working for myself either with a vite setup.
