### ISSUE TITLE
Only blank story rendered

### ISSUE THREAD

**Issue by hirnschmalz** [maraisr/storybook-addon-grid#19]
### Describe the bug

If I enable the addon in a Storybook 8.5.1 project, only blank pages are rendered for my stories. (auto)doc pages are rendered fine. Unfortunately there is no output on the CLI while running in `storybook dev --debug --loglevel silly`

### To reproduce

* Create a new Storybook 8.5.2 project
* Add the Column Guides addon
* Open a story

### Expected behavior

The story should rendered.

**Comment by kuschti** [comment]
any news on this?

**Comment by mak-koda** [comment]
we are having the same issue, any news on this?

**Comment by maraisr** [comment]
Howdy folk, sorry it took so long. But I have published a [bugfix](https://github.com/maraisr/storybook-addon-grid/commit/4c6d9bd3d846fa64ff7c67362522b4d854c51d16) at [storybook-addon-grid@0.5.3](https://www.npmjs.com/package/storybook-addon-grid/v/0.5.3), there seemed to have been a regression with the addon api. 

Please let me know if you are still having issues.

**Comment by mak-koda** [comment]
I still have issues:
![Image](https://github.com/user-attachments/assets/3e7c8221-ecf1-49b3-8a8c-4f4a0f5f5dcd)

Now it breaks the whole storybook, not just when I open a story

**Comment by maraisr** [comment]
That's something I noticed as well, had something to do with React 19. Can you confirm it works with React 18? If so, i'll take another look.

**Comment by mak-koda** [comment]
Yeah it works with React 18 😊

**Comment by mak-koda** [comment]
Can we reopen this issue? since it still doesn't work with React 19

**Comment by maraisr** [comment]
Yeah lets do it.
